services:
  backend:
    build:
      context: ./backend/file_renamer
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/file_renamer:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend/app_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
